config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  root  'home#top'
  resources :sakes
  resources :users
  get 'user_list' => 'user#index'
  get 'graph' => 'reviews#create_graph'

end

app/models/sake.rb
class Sake < ActiveRecord::Base
  has_many :reviews
  validates :name, presence: true,uniqueness: true
  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/sake_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end
end

app/controllers/sakes_controller.rb
class SakesController < ApplicationController
  before_action :set_sake, only: [:show, :edit, :update, :destroy]

  # GET /sakes
  # GET /sakes.json
  def index
    @sakes = Sake.all
  end

  # GET /sakes/1
  # GET /sakes/1.json
  def show
    @reviews = @sake.reviews
    sum_fruity = 0
    sum_taste = 0
    average_fruity = 0
    average_taste = 0
    i = 0

    @reviews.each do |review|
      sum_fruity += review[:fruity].to_i
      sum_taste += review[:taste].to_i
      i += 1
    end
    if i != 0 then
      average_fruity = sum_fruity/i
      average_taste = sum_taste/i
      aData = [[average_fruity, average_taste]]
    
      @graph = LazyHighCharts::HighChart.new('graph') do |f|
        f.chart(scatter: true,zoomType: 'xy') #グラフの種類
        f.pane(size:'10%')                  #グラフサイズの比
        f.title(text: '平均値')   
        f.xAxis(title: {
                  enabled: true,
                  text: '香り'
              },
              startOnTick: true,
              endOnTick: true,
              showLastLabel: true,
              min:-2,max:2
              )#タイトル
        f.yAxis(title: {text: "味"} ,min:-2,max:2) #各項目の最大値やら
        f.series(name:'',data: aData)
        f.legend(
              layout: 'vertical',
              align: 'left',
              verticalAlign: 'top',
              x: 50,
              y: 50,
              floating: true,
              borderWidth: 1
          )
        @graph_comp = 1
      end
  	 else
  	  @graph_comp = 0
  	end
  end
  # GET /sakes/new
  def new
    @sake = Sake.new
  end

  # GET /sakes/1/edit
  def edit
  end

  # POST /sakes
  # POST /sakes.json
  def create
    @sake = Sake.new(sake_params)
    file = params[:sake][:image]
    @sake.set_image(file)
    respond_to do |format|
      if @sake.save
        format.html { redirect_to @sake, notice: '登録完了しました' }
        format.json { render :show, status: :created, location: @sake }
      else
        format.html { render :new }
        format.json { render json: @sake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sakes/1
  # PATCH/PUT /sakes/1.json
  def update
    file = params[:sake][:image]
    @sake.set_image(file)
    respond_to do |format|
      if @sake.update(sake_params)
        format.html { redirect_to @sake, notice: '情報を編集しました' }
        format.json { render :show, status: :ok, location: @sake }
      else
        format.html { render :edit }
        format.json { render json: @sake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sakes/1
  # DELETE /sakes/1.json
  def destroy
    @sake.destroy
    respond_to do |format|
      format.html { redirect_to sakes_url, notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sake
      @sake = Sake.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sake_params
      params.require(:sake).permit(:name, :place, :user_id)
    end
end

app/helpers/sakes_helper.rb
module SakesHelper
  def image_for(user)
    if user.image
      image_tag "/sake_images/#{user.image}", class: "profile_img"
    else
      image_tag "/sake_images/sake_def.jpg", class: "profile_img"
    end
  end
end

app/views/sakes/_form.html.erb
<%= form_for(@sake) do |f| %>
  <% if @sake.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @sake.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @sake.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label  "名前" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "産地" %><br>
    <%= f.text_field :place %>
  </div>
  <div>
    <%= f.label  "ラベル登録" %><br>
    <%= f.file_field :image, class: "form-control image-field" %>
  </div>
  <div class="actions">
    <%= f.submit "登録する"%>
  </div>
<% end %>

app/views/sakes/edit.html.erb
<div class = "content">
<h1>日本酒情報編集</h1>

<%= render 'form' %>

<%= link_to '日本酒一覧', @sake %> |
<%= link_to '戻る', sakes_path %>
</div>

app/views/sakes/index.html.erb
<div class = "content">
  <p id="notice"><%= notice %></p>

<h1>日本酒一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>名前</th>
      <th>産地</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @sakes.each do |sake| %>
      <tr>
        <td><%= sake.name %></td>
        <td><%= sake.place %></td>
        <td><%= link_to '詳細', sake %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日本酒新規登録', new_sake_path %>
</div>

app/views/sakes/new.html.erb
<div class = "content">
  <h1>日本酒新規登録</h1>

<%= render 'form' %>

<%= link_to '一覧へ戻る', sakes_path %>
</div>

app/views/sakes/show.html.erb
<div class = "content">
  <p id="notice"><%= notice %></p>
<%= image_for(@sake)%>
<p>
  <strong>名前:</strong>
  <%= @sake.name %>
</p>

<p>
  <strong>産地:</strong>
  <%= @sake.place %>
</p>
<p>
 </p>
   <strong>感想</strong></strong>
</p>
<ul class="reviews">
  <% @reviews.each do |review| %>
    <li><%= review.comment %></li>
  <% end %>
</ul>
<% if @graph_comp == 1%>
<p>
<%= high_chart("radar", @graph) %>
</p>
<%end%>
<!--<%= link_to '編集', edit_sake_path(@sake) %>-->
<!--<%= link_to '削除', @sake, method: :delete, data: { confirm: '本当に削除してもいいですか?' } %>-->
<%= link_to '一覧へ戻る', sakes_path %>
</div>

app/views/sakes/show_add_review.html.erb
<p id="notice"><%= notice %></p>
<%= image_for(@sake)%>
<p>
  <strong>名前:</strong>
  <%= @sake.name %>
</p>

<p>
  <strong>産地:</strong>
  <%= @sake.place %>
</p>
<p>
  <strong>感想</strong></strong>
</p>
<ul class="reviews">
  <% @reviews = Raview.find(:id) %>
  <% @reviews.each do |review| %>
    <li><%= review %></li>
  <% end %>
</ul>

<%= link_to '一覧へ戻る', sakes_path %>