config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  root  'home#top'
  resources :sakes
  resources :users
  get 'user_list' => 'user#index'
  get 'graph' => 'reviews#create_graph'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @user = @review.user
    @sake = @review.sake
     aData = [[@review.fruity.to_i, @review.taste.to_i]]
    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(scatter: true,zoomType: 'xy') #グラフの種類
      f.pane(size:'10%')                  #グラフサイズの比
      f.title(text: 'あなたの評価')   
      f.xAxis(title: {
                enabled: true,
                text: '香り'
            },
            startOnTick: true,
            endOnTick: true,
            showLastLabel: true,
            min:-2,max:2
            )#タイトル
      f.yAxis(title: {text: "味"} ,min:-2,max:2) #各項目の最大値やら
      f.series(name:'Aさん',data: aData)
      f.legend(
            layout: 'vertical',
            align: 'left',
            verticalAlign: 'top',
            x: 50,
            y: 50,
            floating: true,
            borderWidth: 1
        )
  	end
  end
  
  def create_graph
    
    @reviews = Review.all # すべての日本酒評価の情報が配列
    sum_fruity = 0
    sum_taste = 0
    average_fruity = 0
    average_taste = 0
    i = 0

    @reviews.each do |review|
      sum_fruity += review[:fruity].to_i
      sum_taste += review[:taste].to_i
      i += 1
    end
    
    average_fruity = sum_fruity/i
    average_taste = sum_taste/i
    aData = [[average_fruity, average_taste]]
    
    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(scatter: true,zoomType: 'xy') #グラフの種類
      f.pane(size:'10%')                  #グラフサイズの比
      f.title(text: '')   
      f.xAxis(title: {
                enabled: true,
                text: '香り'
            },
            startOnTick: true,
            endOnTick: true,
            showLastLabel: true,
            min:-2,max:2
            )#タイトル
      f.yAxis(title: {text: "味"} ,min:-2,max:2) #各項目の最大値やら
      f.series(name:'',data: aData)
      f.legend(
            layout: 'vertical',
            align: 'left',
            verticalAlign: 'top',
            x: 50,
            y: 50,
            floating: true,
            borderWidth: 1
        )
  	end
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: '投稿できました.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: '修正しました' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: '消去しました.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_id, :sake_id, :comment,:fruity,:taste)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @review.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label "日本酒名" %><br>
    <%= f.collection_select :sake_id, Sake.all, :id, :name, {prompt: true}, {class: "form-control sake-id-field"} %>
  </div>
  <div class="field">
    <%= f.label "ユーザ名" %><br>
    <%= f.collection_select :user_id, User.all, :id, :name, {prompt: true}, {class: "form-control user-id-field"} %>
  </div>
  <div class="field">
    <%= f.label "香り" %><br>
    <%= f.select :fruity, options_for_select([-2, -1, 0, 1, 2]), {class: "form-control user-id-field"} %>
  </div>
  <div class="field">
    <%= f.label "味" %><br>
    <%= f.select :taste, options_for_select([-2, -1, 0, 1, 2]), {class: "form-control user-id-field"} %>
  </div>
  <div class="field">
    <%= f.label "コメント" %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit "保存", { class: "btn primary-btn" } %>
  </div>
<% end %>

app/views/reviews/create_graph.html.erb
<h1>Graph#create_graph</h1>
<%= high_chart("radar", @graph) %>

app/views/reviews/edit.html.erb
<div class = "content">
<h1>投稿を編集する</h1>

<%= render 'form' %>

<%= link_to '戻る', reviews_path %>
</div>

app/views/reviews/index.html.erb
<div class = "content">
<p id="notice"><%= notice %></p>

<h1>投稿の一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>日本酒名</th>
      <th>コメント</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <% @sake = Sake.find(review.sake_id) %>
      <tr>
        <td><%= @sake.name%></td>
        <td><%= review.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/reviews/new.html.erb
<div class = "content">
  <h1>レビュー登録</h1>

<%= render 'form' %>

<%= link_to 'トップへ戻る', root_path %>
</div>

app/views/reviews/show.html.erb
<div class = "content"><p id="notice"><%= notice %></p>

<p>
  <strong>日本酒:</strong>
  <%= @sake.name %>
</p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>コメント:</strong>
  <%= @review.comment %>
</p>
<p>
<%= high_chart("radar", @graph) %>
</p>
<%= link_to "戻る", reviews_path, class: "btn index-btn" %>
<!--<%= link_to "編集", edit_review_path(@review.id), class: "btn edit-btn" %>-->
<!--<%= link_to "削除", review_path(@review.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>-->
</div>