config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  root  'home#top'
  resources :sakes
  resources :users
  get 'user_list' => 'user#index'
  get 'graph' => 'reviews#create_graph'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>sakacloud-酒蔵人-</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

<body>
  <header class="navbar">
    <div class="container">
      <div id="logo"><img class="logo" src="/sakacloud_logo3.png"></div>
      <!--<div id="logo">sakacloud-酒蔵人-</div>-->
      <ul class="header-right nav nav-pills">
        <li><%= link_to "トップ ", root_path %></li>
        <li><%= link_to "ユーザー登録 ", new_user_path %></li>
        <li><%= link_to "ユーザ一覧 ", users_path %></li>
        <li><%= link_to "日本酒投稿 ", new_sake_path %></li>
        <li><%= link_to "日本酒一覧 ", sakes_path %></li>
        <li><%= link_to "レビュー", new_review_path %></li>
      </ul>
        
      </ul>
    </div>
  </header>
  
  <%= yield %>
  
  </div>
<footer>
  <div class="panel panel-default">
    <div class="panel-footer footer">© 2016 sakacloud @AGL</div>
  </div>
</footer>



</body>
</html>